# Reason this exists: Github doesn't pass repo secrets to untrusted PRs (e.g. PRs from forked repos) since it's untrusted code and we can't guarantee
#  that the untrusted code won't leak secrets. Kurtosis needs an API secret to run, so this means that PRs from forked repos won't get their Kurtosis
#  CI checks run. This is a bad experience.
# To resolve this, we use nwtgck's approach on https://github.community/t/secrets-for-prs-who-are-not-collaborators/17712/11 , where a codeowner will
#  first review the code, verify it doesn't leak any secrets, and then use Github Actions to create a new PR containing the untrusted PR's code. Because
#  the PR will be submitted by a codeowner, the secrets will be passed to the CI environment and Kurtosis can run.
name: "Comment run"
on:
  issue_comment:
    types: [created, edited]

jobs:
  comment-run:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        # 0 indicates all history
        fetch-depth: 0
    - uses: mieubrisse/actions-comment-run@mieubrisse/disjunctive-whitelisted-users
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allowed-associations: '["OWNER"]'
        whitelisted-users: '["mieubrisse"]'
